name: salesforce
description: "Trade B2B"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  http: ^1.5.0
  dartz: ^0.10.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_svg: ^2.2.0
  google_maps_flutter: ^2.12.3
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  connectivity_plus: ^6.1.5
  path: ^1.9.1
  permission_handler: ^12.0.1
  carousel_slider: ^5.1.1
  flutter_local_notifications: ^19.4.0
  url_launcher: ^6.3.2
  get_it: ^8.2.0
  onesignal_flutter: ^5.3.4
  package_info_plus: ^8.3.1
  mobile_scanner: ^7.0.1
  image: ^4.5.4
  share_plus: ^11.1.0
  google_mlkit_barcode_scanning: ^0.14.1
  camera: ^0.11.2
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  esc_pos_utils_plus: ^2.0.4
  flutter_blue_plus: ^1.35.10
  device_info_plus: ^12.1.0
  realm: ^20.1.1
  pinput: ^5.0.2
  country_code_picker: ^3.4.0
  workmanager: ^0.9.0+3
  print_bluetooth_thermal: ^1.1.7
  app_settings: ^6.1.1
  # imin_printer: ^0.6.14
  # characters: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/process_icon/
    
  fonts:
    - family: Siemreap
      fonts:
        - asset: assets/fonts/Siemreap-Regular.ttf

    - family: NotoSansKhmer
      fonts:
        - asset: assets/fonts/NotoSansKhmer-Regular.ttf      
